<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class Countries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //

        Schema::create('countries', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';

            $table->id();
            $table->string('countryName');
            $table->timestamps();
        });

        // Insert some stuff
        DB::table('countries')->insert(
            array(
                ["countryName" => "Afghanistan",],
                ["countryName" => "Åland Islands",],
                ["countryName" => "Albania",],
                ["countryName" => "Algeria",],
                ["countryName" => "American Samoa",],
                ["countryName" => "Andorra",],
                ["countryName" => "Angola",],
                ["countryName" => "Anguilla",],
                ["countryName" => "Antarctica",],
                ["countryName" => "Antigua and Barbuda",],
                ["countryName" => "Argentina",],
                ["countryName" => "Armenia",],
                ["countryName" => "Aruba",],
                ["countryName" => "Australia",],
                ["countryName" => "Austria",],
                ["countryName" => "Azerbaijan",],
                ["countryName" => "Bahamas",],
                ["countryName" => "Bahrain",],
                ["countryName" => "Bangladesh",],
                ["countryName" => "Barbados",],
                ["countryName" => "Belarus",],
                ["countryName" => "Belgium",],
                ["countryName" => "Belize",],
                ["countryName" => "Benin",],
                ["countryName" => "Bermuda",],
                ["countryName" => "Bhutan",],
                ["countryName" => "Bolivia",],
                ["countryName" => "Bosnia and Herzegovina",],
                ["countryName" => "Botswana",],
                ["countryName" => "Bouvet Island",],
                ["countryName" => "Brazil",],
                ["countryName" => "British Indian Ocean Territory",],
                ["countryName" => "Brunei Darussalam",],
                ["countryName" => "Bulgaria",],
                ["countryName" => "Burkina Faso",],
                ["countryName" => "Burundi",],
                ["countryName" => "Cambodia",],
                ["countryName" => "Cameroon",],
                ["countryName" => "Canada",],
                ["countryName" => "Cape Verde",],
                ["countryName" => "Cayman Islands",],
                ["countryName" => "Central African Republic",],
                ["countryName" => "Chad",],
                ["countryName" => "Chile",],
                ["countryName" => "China",],
                ["countryName" => "Christmas Island",],
                ["countryName" => "Cocos (Keeling) Islands",],
                ["countryName" => "Colombia",],
                ["countryName" => "Comoros",],
                ["countryName" => "Congo",],
                ["countryName" => "Congo, The Democratic Republic of The",],
                ["countryName" => "Cook Islands",],
                ["countryName" => "Costa Rica",],
                ["countryName" => "Cote D'ivoire",],
                ["countryName" => "Croatia",],
                ["countryName" => "Cuba",],
                ["countryName" => "Cyprus",],
                ["countryName" => "Czech Republic",],
                ["countryName" => "Denmark",],
                ["countryName" => "Djibouti",],
                ["countryName" => "Dominica",],
                ["countryName" => "Dominican Republic",],
                ["countryName" => "Ecuador",],
                ["countryName" => "Egypt",],
                ["countryName" => "El Salvador",],
                ["countryName" => "Equatorial Guinea",],
                ["countryName" => "Eritrea",],
                ["countryName" => "Estonia",],
                ["countryName" => "Ethiopia",],
                ["countryName" => "Falkland Islands (Malvinas)",],
                ["countryName" => "Faroe Islands",],
                ["countryName" => "Fiji",],
                ["countryName" => "Finland",],
                ["countryName" => "France",],
                ["countryName" => "French Guiana",],
                ["countryName" => "French Polynesia",],
                ["countryName" => "French Southern Territories",],
                ["countryName" => "Gabon",],
                ["countryName" => "Gambia",],
                ["countryName" => "Georgia",],
                ["countryName" => "Germany",],
                ["countryName" => "Ghana",],
                ["countryName" => "Gibraltar",],
                ["countryName" => "Greece",],
                ["countryName" => "Greenland",],
                ["countryName" => "Grenada",],
                ["countryName" => "Guadeloupe",],
                ["countryName" => "Guam",],
                ["countryName" => "Guatemala",],
                ["countryName" => "Guernsey",],
                ["countryName" => "Guinea",],
                ["countryName" => "Guinea-bissau",],
                ["countryName" => "Guyana",],
                ["countryName" => "Haiti",],
                ["countryName" => "Heard Island and Mcdonald Islands",],
                ["countryName" => "Holy See (Vatican City State)",],
                ["countryName" => "Honduras",],
                ["countryName" => "Hong Kong",],
                ["countryName" => "Hungary",],
                ["countryName" => "Iceland",],
                ["countryName" => "India",],
                ["countryName" => "Indonesia",],
                ["countryName" => "Iran, Islamic Republic of",],
                ["countryName" => "Iraq",],
                ["countryName" => "Ireland",],
                ["countryName" => "Isle of Man",],
                ["countryName" => "Israel",],
                ["countryName" => "Italy",],
                ["countryName" => "Jamaica",],
                ["countryName" => "Japan",],
                ["countryName" => "Jersey",],
                ["countryName" => "Jordan",],
                ["countryName" => "Kazakhstan",],
                ["countryName" => "Kenya",],
                ["countryName" => "Kiribati",],
                ["countryName" => "Korea, Democratic People's Republic of",],
                ["countryName" => "Korea, Republic of",],
                ["countryName" => "Kuwait",],
                ["countryName" => "Kyrgyzstan",],
                ["countryName" => "Lao People's Democratic Republic",],
                ["countryName" => "Latvia",],
                ["countryName" => "Lebanon",],
                ["countryName" => "Lesotho",],
                ["countryName" => "Liberia",],
                ["countryName" => "Libyan Arab Jamahiriya",],
                ["countryName" => "Liechtenstein",],
                ["countryName" => "Lithuania",],
                ["countryName" => "Luxembourg",],
                ["countryName" => "Macao",],
                ["countryName" => "Macedonia, The Former Yugoslav Republic of",],
                ["countryName" => "Madagascar",],
                ["countryName" => "Malawi",],
                ["countryName" => "Malaysia",],
                ["countryName" => "Maldives",],
                ["countryName" => "Mali",],
                ["countryName" => "Malta",],
                ["countryName" => "Marshall Islands",],
                ["countryName" => "Martinique",],
                ["countryName" => "Mauritania",],
                ["countryName" => "Mauritius",],
                ["countryName" => "Mayotte",],
                ["countryName" => "Mexico",],
                ["countryName" => "Micronesia, Federated States of",],
                ["countryName" => "Moldova, Republic of",],
                ["countryName" => "Monaco",],
                ["countryName" => "Mongolia",],
                ["countryName" => "Montenegro",],
                ["countryName" => "Montserrat",],
                ["countryName" => "Morocco",],
                ["countryName" => "Mozambique",],
                ["countryName" => "Myanmar",],
                ["countryName" => "Namibia",],
                ["countryName" => "Nauru",],
                ["countryName" => "Nepal",],
                ["countryName" => "Netherlands",],
                ["countryName" => "Netherlands Antilles",],
                ["countryName" => "New Caledonia",],
                ["countryName" => "New Zealand",],
                ["countryName" => "Nicaragua",],
                ["countryName" => "Niger",],
                ["countryName" => "Nigeria",],
                ["countryName" => "Niue",],
                ["countryName" => "Norfolk Island",],
                ["countryName" => "Northern Mariana Islands",],
                ["countryName" => "Norway",],
                ["countryName" => "Oman",],
                ["countryName" => "Pakistan",],
                ["countryName" => "Palau",],
                ["countryName" => "Palestinian Territory, Occupied",],
                ["countryName" => "Panama",],
                ["countryName" => "Papua New Guinea",],
                ["countryName" => "Paraguay",],
                ["countryName" => "Peru",],
                ["countryName" => "Philippines",],
                ["countryName" => "Pitcairn",],
                ["countryName" => "Poland",],
                ["countryName" => "Portugal",],
                ["countryName" => "Puerto Rico",],
                ["countryName" => "Qatar",],
                ["countryName" => "Reunion",],
                ["countryName" => "Romania",],
                ["countryName" => "Russian Federation",],
                ["countryName" => "Rwanda",],
                ["countryName" => "Saint Helena",],
                ["countryName" => "Saint Kitts and Nevis",],
                ["countryName" => "Saint Lucia",],
                ["countryName" => "Saint Pierre and Miquelon",],
                ["countryName" => "Saint Vincent and The Grenadines",],
                ["countryName" => "Samoa",],
                ["countryName" => "San Marino",],
                ["countryName" => "Sao Tome and Principe",],
                ["countryName" => "Saudi Arabia",],
                ["countryName" => "Senegal",],
                ["countryName" => "Serbia",],
                ["countryName" => "Seychelles",],
                ["countryName" => "Sierra Leone",],
                ["countryName" => "Singapore",],
                ["countryName" => "Slovakia",],
                ["countryName" => "Slovenia",],
                ["countryName" => "Solomon Islands",],
                ["countryName" => "Somalia",],
                ["countryName" => "South Africa",],
                ["countryName" => "South Georgia and The South Sandwich Islands",],
                ["countryName" => "Spain",],
                ["countryName" => "Sri Lanka",],
                ["countryName" => "Sudan",],
                ["countryName" => "Suriname",],
                ["countryName" => "Svalbard and Jan Mayen",],
                ["countryName" => "Swaziland",],
                ["countryName" => "Sweden",],
                ["countryName" => "Switzerland",],
                ["countryName" => "Syrian Arab Republic",],
                ["countryName" => "Taiwan",],
                ["countryName" => "Tajikistan",],
                ["countryName" => "Tanzania, United Republic of",],
                ["countryName" => "Thailand",],
                ["countryName" => "Timor-leste",],
                ["countryName" => "Togo",],
                ["countryName" => "Tokelau",],
                ["countryName" => "Tonga",],
                ["countryName" => "Trinidad and Tobago",],
                ["countryName" => "Tunisia",],
                ["countryName" => "Turkey",],
                ["countryName" => "Turkmenistan",],
                ["countryName" => "Turks and Caicos Islands",],
                ["countryName" => "Tuvalu",],
                ["countryName" => "Uganda",],
                ["countryName" => "Ukraine",],
                ["countryName" => "United Arab Emirates",],
                ["countryName" => "United Kingdom",],
                ["countryName" => "United States",],
                ["countryName" => "United States Minor Outlying Islands",],
                ["countryName" => "Uruguay",],
                ["countryName" => "Uzbekistan",],
                ["countryName" => "Vanuatu",],
                ["countryName" => "Venezuela",],
                ["countryName" => "Viet Nam",],
                ["countryName" => "Virgin Islands, British",],
                ["countryName" => "Virgin Islands, U.S.",],
                ["countryName" => "Wallis and Futuna",],
                ["countryName" => "Western Sahara",],
                ["countryName" => "Yemen",],
                ["countryName" => "Zambia",],
                ["countryName" => "Zimbabwe"],
            )
        );
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
